name: GitHub Analytics Charts

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Contribution Chart
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, repositories
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_activity: yes
          plugin_activity_limit: 31
